### ISSUE TITLE
quota: usage values can apparently go below zero 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-db#188]
A problem seen on PROD: user quota usage numbers can go negative for a reason or another.

To reproduce this locally, do:

1. Create a user with some individual disk quota:

```
$ kubectl exec -i -t deployment/reana-server -c rest-api -- flask reana-admin user-create -e tibor@localhost --admin-access-token $REANA_ACCESS_TOKEN
$ kubectl exec -i -t deployment/reana-server -c rest-api -- flask reana-admin quota-set -e tibor@localhost -r disk -l 100000000000
```

2. Login as this new user and launch one workflow:

```
$ reana-client quota-show --resource disk -h
0 Bytes out of 93.13 GiB used (0%)

$ reana-client run -w roofit
...

$ reana-client list --include-workspace-size
NAME     RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     SIZE
roofit   1            2023-01-05T13:25:48   2023-01-05T13:25:59   2023-01-05T13:26:18   finished   -1

$ kubectl create job --from cronjob/reana-resource-quota-update force-quota-update

$ reana-client quota-show --resource disk -h
180 KiB out of 93.13 GiB used (0%)

$ reana-client quota-show --resource disk
184320 out of 100000000000 used (0%)
```

3. Fake the DB status to simulate negative quota (which was seen on PROD by user having many workflows, some failed, and deleted everything):

```
$ kubectl exec -i -t deployment/reana-db -- psql -U reana
reana=# update __reana.user_resource set quota_used=-100 where quota_limit=100000000000 and quota_used=184320;
```

4. The user now cannot connect to the system:

```
$ reana-client ping
REANA server: https://localhost:30443
REANA server version:
REANA client version: 0.9.0a8
Authenticated as:  <None>
Status: ERROR: INVALID ACCESS TOKEN
```

This is due to a traceback:

```
$ kubectl logs reana-server-57546597cc-dx85t rest-api
...
2023-01-05 14:17:35,621 | root | uWSGIWorker6Core0 | ERROR | Traceback (most recent call last):
  File "/code/./reana_server/rest/users.py", line 204, in get_you
    "quota": user.get_quota_usage(),
  File "/code/modules/reana-db/reana_db/models.py", line 131, in get_quota_usage
    return {
  File "/code/modules/reana-db/reana_db/models.py", line 132, in <dictcomp>
    resource_type.name: self._get_quota_by_type(resource_type)
  File "/code/modules/reana-db/reana_db/models.py", line 116, in _get_quota_by_type
    "human_readable": ResourceUnit.human_readable_unit(unit, quota_usage),
  File "/code/modules/reana-db/reana_db/models.py", line 1041, in human_readable_unit
    return convert_to_human_readable[unit](value)
  File "/code/modules/reana-db/reana_db/models.py", line 1024, in _human_readable_bytes
    unit_index = int(math.floor(math.log(bytes_) / math.log(k)))
ValueError: math domain error
```

Notes:

- We should fix the math to account for the fact that the DB column may for a reason or another contain negative values.

- In addition, we should amend the DB column updating logic to make sure that the usage value would never go below zero, ideally. This could be done either by a DB model constraint, which would also need an Alembic recipe, or perhaps we can simply fix this on the app update level only.

**Comment by tiborsimko** [comment]
WRT 3 above, I managed to reproduce the problem by _deleting restarted workflows_. 

Here is how to reproduce the problem cleanly without manually altering the DB values:

```console
$ kubectl create job --from cronjob/reana-resource-quota-update force-quota-update-10

$ reana-client quota-show --resource disk
0 out of 100000000000 used (0%)

$ reana-client run -w hello

$ reana-client list -w hello --include-workspace-size
NAME    RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     SIZE
hello   1            2023-01-05T14:30:49   2023-01-05T14:31:01   2023-01-05T14:31:46   finished   -1

$ kubectl create job --from cronjob/reana-resource-quota-update force-quota-update-11

$ reana-client quota-show --resource disk
16384 out of 100000000000 used (0%)

reana=# select * from __reana.user_resource where quota_limit=100000000000;
          created           |          updated           |               user_id                |             resource_id              | quota_limit  | quota_used
----------------------------+----------------------------+--------------------------------------+--------------------------------------+--------------+------------
 2023-01-05 14:13:51.429366 | 2023-01-05 14:32:19.391653 | ab008a94-d2b9-4549-abb4-e07028f12ca5 | bfec4361-7915-42b0-9ca7-5a1bcec3ff35 | 100000000000 |      16384

$ reana-client restart -w hello

$ kubectl create job --from cronjob/reana-resource-quota-update force-quota-update-12
job.batch/force-quota-update-12 created

$ reana-client list -w hello --include-workspace-size
NAME    RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     SIZE
hello   1.1          2023-01-05T14:33:31   2023-01-05T14:33:42   2023-01-05T14:34:25   finished   16384
hello   1            2023-01-05T14:30:49   2023-01-05T14:31:01   2023-01-05T14:31:46   finished   16384

$ reana-client quota-show --resource disk
16384 out of 100000000000 used (0%)

reana=# select * from __reana.user_resource where quota_limit=100000000000;
          created           |          updated          |               user_id                |             resource_id              | quota_limit  | quota_used
----------------------------+---------------------------+--------------------------------------+--------------------------------------+--------------+------------
 2023-01-05 14:13:51.429366 | 2023-01-05 14:34:40.62355 | ab008a94-d2b9-4549-abb4-e07028f12ca5 | bfec4361-7915-42b0-9ca7-5a1bcec3ff35 | 100000000000 |      16384
(1 row)

$ reana-client delete -w hello.1.1
$ reana-client delete -w hello.1

reana=# select * from __reana.user_resource where quota_limit=100000000000;
          created           |          updated           |               user_id                |             resource_id              | quota_limit  | quota_used
----------------------------+----------------------------+--------------------------------------+--------------------------------------+--------------+------------
 2023-01-05 14:13:51.429366 | 2023-01-05 14:35:34.478887 | ab008a94-d2b9-4549-abb4-e07028f12ca5 | bfec4361-7915-42b0-9ca7-5a1bcec3ff35 | 100000000000 |     -16384
(1 row)

$ reana-client quota-show --resource disk
==> ERROR: Something went wrong while retrieving quota related data

$ reana-client ping
REANA server: https://localhost:30443
REANA server version:
REANA client version: 0.9.0a8
Authenticated as:  <None>
Status: ERROR: INVALID ACCESS TOKEN
```
